# For closed set accuracy
      # 53.67% python train.py CIFAR100 --max_rounds 1 --verbose False --log_everything False --log_first_round_thresholds False --log_test_accuracy True --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # 53.8% python train.py CIFAR100 --max_rounds 1 --verbose False --log_everything False --log_first_round_thresholds False --log_test_accuracy True --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # 53.7% python train.py CIFAR100 --max_rounds 1 --verbose False --log_everything False --log_first_round_thresholds False --log_test_accuracy True --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # 54.4% python train.py CIFAR100 --max_rounds 1 --verbose False --log_everything False --log_first_round_thresholds False --log_test_accuracy True --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # 51.2% python train.py CIFAR100 --max_rounds 1 --icalr_mode default --icalr_strategy proto --save_ckpt False --verbose True --log_everything False --log_test_accuracy True --init_mode no_learning_9K --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure random_query --wd 5e-4;
      # 51.3% python train.py CIFAR100 --max_rounds 1 --icalr_mode default --icalr_strategy proto --save_ckpt False --verbose True --log_everything False --log_test_accuracy True --init_mode no_learning_9K_randomsample --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.05 --lr_decay_step 160 --uncertainty_measure random_query --epochs 200 --wd 5e-4;
      # 51.6% python train.py CIFAR100 --max_rounds 1 --icalr_mode default --icalr_strategy naive --save_ckpt False --verbose True --log_everything False --log_test_accuracy True --init_mode no_learning_9K --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure random_query --wd 5e-4;
      # 51.6% Seen class python train.py CIFAR100 --max_rounds 1 --icalr_mode default --icalr_strategy naive --save_ckpt False --verbose True --log_everything False --log_test_accuracy True --init_mode no_learning_9K_randomsample --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.05 --lr_decay_step 160 --uncertainty_measure random_query --epochs 200 --wd 5e-4;

# For closed set accuracy 8280 samples
      # 51.8% python train.py CIFAR100 --max_rounds 1 --verbose False --log_everything False --log_first_round_thresholds False --log_test_accuracy True --init_mode no_learning_8280 --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # 53.4% python train.py CIFAR100 --max_rounds 1 --verbose False --log_everything False --log_first_round_thresholds False --log_test_accuracy True --init_mode no_learning_8280_randomsample --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # 51.8% python train.py CIFAR100 --max_rounds 1 --verbose False --log_everything False --log_first_round_thresholds False --log_test_accuracy True --init_mode no_learning_8280 --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # 52.7% python train.py CIFAR100 --max_rounds 1 --verbose False --log_everything False --log_first_round_thresholds False --log_test_accuracy True --init_mode no_learning_8280_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # 48.1% python train.py CIFAR100 --max_rounds 1 --icalr_mode default --icalr_strategy proto --save_ckpt False --verbose True --log_everything False --log_test_accuracy True --init_mode no_learning_8280 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure random_query --wd 5e-4;
      # 49.6% python train.py CIFAR100 --max_rounds 1 --icalr_mode default --icalr_strategy proto --save_ckpt False --verbose True --log_everything False --log_test_accuracy True --init_mode no_learning_8280_randomsample --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.05 --lr_decay_step 160 --uncertainty_measure random_query --epochs 200 --wd 5e-4;
      # 48.6% python train.py CIFAR100 --max_rounds 1 --icalr_mode default --icalr_strategy naive --save_ckpt False --verbose True --log_everything False --log_test_accuracy True --init_mode no_learning_8280 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure random_query --wd 5e-4;
      # 49.97% python train.py CIFAR100 --max_rounds 1 --icalr_mode default --icalr_strategy naive --save_ckpt False --verbose True --log_everything False --log_test_accuracy True --init_mode no_learning_8280_randomsample --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.0 --arch ResNet18 --lr 0.05 --lr_decay_step 160 --uncertainty_measure random_query --epochs 200 --wd 5e-4;

# no_learning_5K_50_open_classes
# Not random samples
      # Softmax not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --save_first_round_model;
      # Binary Softmax not pretrained
      # python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer binary_softmax --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Entropy not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer network --threshold_metric entropy --network_eval_mode dynamic_threshold --batch 128 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # ICALR Softmax not pretrained proto
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto --save_first_round_model;
      # ICALR Entropy not pretrained proto
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer icalr --threshold_metric entropy --batch 128 --network_eval_mode dynamic_threshold --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Binary Softmax Proto not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode fixed_variance --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # Sigmoid + mean 
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer sigmoid --batch 128 --network_eval_threshold 0.5 --arch ResNet50 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --sigmoid_train_mode mean;
      # OSDN
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20;
      # OSDN Modified
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20;
      # ICALR OSDN proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # ICALR OSDN Modified proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_5K_50_open_classes --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20 --icalr_strategy proto;


# Not random samples
      # Softmax not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Binary Softmax not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer binary_softmax --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Entropy not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer network --threshold_metric entropy --network_eval_mode dynamic_threshold --batch 128 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # ICALR Softmax not pretrained proto
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Entropy not pretrained proto
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr --threshold_metric entropy --batch 128 --network_eval_mode dynamic_threshold --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Binary Softmax Naive not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode default --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy naive;
      # ICALR Binary Softmax Proto not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode default --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # Sigmoid + mean 
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer sigmoid --batch 128 --network_eval_threshold 0.5 --arch ResNet50 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --sigmoid_train_mode mean;
      # OSDN
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      # EUCOS + pseudo threshold + metric weighted alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted;
      # EUCOS + pseudo threshold + metric average alpha rank 5
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average;
      # OSDN Modified
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      # EUCOS + pseudo threshold + weighted metric alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted;
      # EUCOS + pseudo threshold + average metric alpha rank 5
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average;
      # ICALR OSDN proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # EUCOS + pseudo threshold + metric weighted alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted --icalr_strategy proto;
      # EUCOS + pseudo threshold + metric average alpha rank 5
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average --icalr_strategy proto;
      # ICALR OSDN Modified proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # EUCOS + pseudo threshold + weighted metric alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted --icalr_strategy proto;
      # EUCOS + pseudo threshold + average metric alpha rank 5
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average --icalr_strategy proto;

      # Uniform sample
            # OSDN
            # EUCOS + threshold 0.1
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_5 --weibull_tail_size fixed_20;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_20 --weibull_tail_size fixed_20;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_40 --weibull_tail_size fixed_20;
            # OSDN Modified
            # EUCOS + threshold 0.1
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_5 --weibull_tail_size fixed_20;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_20 --weibull_tail_size fixed_20;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_40 --weibull_tail_size fixed_20;
            # ICALR OSDN Proto
            # EUCOS + threshold 0.1
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20 --icalr_strategy proto;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_5 --weibull_tail_size fixed_20 --icalr_strategy proto;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_20 --weibull_tail_size fixed_20 --icalr_strategy proto;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_40 --weibull_tail_size fixed_20 --icalr_strategy proto;
            # ICALR OSDN Modified Proto
            # EUCOS + threshold 0.1
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20 --icalr_strategy proto;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_5 --weibull_tail_size fixed_20 --icalr_strategy proto;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_20 --weibull_tail_size fixed_20 --icalr_strategy proto;
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_40 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # Random sample
            # OSDN
            # EUCOS + threshold 0.1
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_5 --weibull_tail_size fixed_20;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_20 --weibull_tail_size fixed_20;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_40 --weibull_tail_size fixed_20;
            # OSDN Modified
            # EUCOS + threshold 0.1
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_5 --weibull_tail_size fixed_20;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_20 --weibull_tail_size fixed_20;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_40 --weibull_tail_size fixed_20;
            # ICALR OSDN Proto
            # EUCOS + threshold 0.1
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20 --icalr_strategy proto;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_5 --weibull_tail_size fixed_20 --icalr_strategy proto;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_20 --weibull_tail_size fixed_20 --icalr_strategy proto;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_40 --weibull_tail_size fixed_20 --icalr_strategy proto;
            # ICALR OSDN Modified Proto
            # EUCOS + threshold 0.1
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_2 --weibull_tail_size fixed_20 --icalr_strategy proto;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_5 --weibull_tail_size fixed_20 --icalr_strategy proto;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_20 --weibull_tail_size fixed_20 --icalr_strategy proto;
            CUDA_VISIBLE_DEVICES=1 python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_40 --weibull_tail_size fixed_20 --icalr_strategy proto;

# random samples
      # Softmax not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Binary Softmax not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer binary_softmax --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Entropy not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer network --threshold_metric entropy --network_eval_mode dynamic_threshold --batch 128 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # ICALR Softmax not pretrained proto
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Entropy not pretrained proto
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr --threshold_metric entropy --batch 128 --network_eval_mode dynamic_threshold --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Binary Softmax Naive not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode default --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy naive;
      # ICALR Binary Softmax Proto not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode default --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # Sigmoid + mean 
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer sigmoid --batch 128 --network_eval_threshold 0.5 --arch ResNet50 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --sigmoid_train_mode mean;
      # OSDN
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      # EUCOS + pseudo threshold + metric weighted alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted;
      # EUCOS + pseudo threshold + metric average alpha rank 5
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average;
      # OSDN Modified
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      # EUCOS + pseudo threshold + weighted metric alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted;
      # EUCOS + pseudo threshold + average metric alpha rank 5
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average;
      # ICALR OSDN Proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # EUCOS + pseudo threshold + metric weighted alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted --icalr_strategy proto;
      # EUCOS + pseudo threshold + metric average alpha rank 5
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average --icalr_strategy proto;
      # ICALR OSDN Modified Proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # EUCOS + pseudo threshold + weighted metric alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted --icalr_strategy proto;
      # EUCOS + pseudo threshold + average metric alpha rank 5
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average --icalr_strategy proto;
