# Not random samples
      # Softmax not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Binary Softmax not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer binary_softmax --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Entropy not pretrained
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer network --threshold_metric entropy --network_eval_mode dynamic_threshold --batch 128 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # ICALR Softmax not pretrained proto
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Entropy not pretrained proto
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr --threshold_metric entropy --batch 128 --network_eval_mode dynamic_threshold --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Binary Softmax Naive not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode default --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy naive;
      # ICALR Binary Softmax Proto not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode default --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # Sigmoid + mean 
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer sigmoid --batch 128 --network_eval_threshold 0.5 --arch ResNet50 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --sigmoid_train_mode mean;
      # OSDN
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      # EUCOS + pseudo threshold + metric weighted alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted;
      # EUCOS + pseudo threshold + metric average alpha rank 5
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average;
      # OSDN Modified
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      # EUCOS + pseudo threshold + weighted metric alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted;
      # EUCOS + pseudo threshold + average metric alpha rank 5
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average;
      # ICALR OSDN proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # EUCOS + pseudo threshold + metric weighted alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted --icalr_strategy proto;
      # EUCOS + pseudo threshold + metric average alpha rank 5
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average --icalr_strategy proto;
      # ICALR OSDN Modified proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # EUCOS + pseudo threshold + weighted metric alpha rank 2
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted --icalr_strategy proto;
      # EUCOS + pseudo threshold + average metric alpha rank 5
            python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average --icalr_strategy proto;

# random samples
      # Softmax not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer network --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Binary Softmax not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer binary_softmax --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # Entropy not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer network --threshold_metric entropy --network_eval_mode dynamic_threshold --batch 128 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident;
      # ICALR Softmax not pretrained proto
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Entropy not pretrained proto
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr --threshold_metric entropy --batch 128 --network_eval_mode dynamic_threshold --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # ICALR Binary Softmax Naive not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode default --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy naive;
      # ICALR Binary Softmax Proto not pretrained
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_binary_softmax --icalr_binary_softmax_train_mode default --batch 128 --network_eval_threshold 0.1 --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --icalr_strategy proto;
      # Sigmoid + mean 
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer sigmoid --batch 128 --network_eval_threshold 0.5 --arch ResNet50 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --sigmoid_train_mode mean;
      # OSDN
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      # EUCOS + pseudo threshold + metric weighted alpha rank 2
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted;
      # EUCOS + pseudo threshold + metric average alpha rank 5
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average;
      # OSDN Modified
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20;
      # EUCOS + pseudo threshold + weighted metric alpha rank 2
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted;
      # EUCOS + pseudo threshold + average metric alpha rank 5
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average;
      # ICALR OSDN Proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # EUCOS + pseudo threshold + metric weighted alpha rank 2
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted --icalr_strategy proto;
      # EUCOS + pseudo threshold + metric average alpha rank 5
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average --icalr_strategy proto;
      # ICALR OSDN Modified Proto
      # EUCOS + threshold 0.1
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --osdn_eval_threshold 0.1 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos --alpha_rank fixed_10 --weibull_tail_size fixed_20 --icalr_strategy proto;
      # EUCOS + pseudo threshold + weighted metric alpha rank 2
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric weighted --icalr_strategy proto;
      # EUCOS + pseudo threshold + average metric alpha rank 5
      python train.py CIFAR100 --verbose False --log_everything True --log_first_round_thresholds True --log_test_accuracy False --init_mode no_learning_9K_randomsample --writer False --save_ckpt False --data_path ./data --trainer icalr_osdn_modified --batch 128 --mav_features_selection none_correct_then_all --arch ResNet18 --lr 0.1 --epochs 200 --lr_decay_step 160 --uncertainty_measure least_confident --distance_metric eucos  --pseudo_open_set 1 --pseudo_open_set_rounds 500 --openmax_meta_learn open_set --pseudo_open_set_metric average --icalr_strategy proto;
