# CIFAR10 Stratified
    # Coreset Cosine (Seed: None, 1, 10, 100, 1000, 2000)
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Coreset (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Random (Seed: None, 1, 10, 100, 1000, 2000)
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Softmax (Seed: None, 1, 10, 100, 1000, 2000)
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Entropy (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # ULDR (Seed: None, 1, 10, 100, 1000, 2000)
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # ULDR Cosine (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed None --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 1 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 10 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 100 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 1000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR10 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 2000 --data_download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True







#CIFAR 100 Stratified
    # Coreset Cosine (Seed: None, 1, 10, 100, 1000, 2000)
        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Coreset (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method coreset --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Random (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method random --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method random --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Softmax (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method softmax --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Entropy (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method entropy --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # ULDR (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # ULDR Cosine (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed None --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 1 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 10 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 100 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 1000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python start_active_learning.py CIFAR100 --training_method softmax_network --data_config active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --data_rand_seed 2000 --data_download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True


