# CIFAR10 Stratified
    # Coreset Cosine (Seed: None, 1, 10, 100, 1000, 2000)
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Coreset (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Random (Seed: None, 1, 10, 100, 1000, 2000)
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Softmax (Seed: None, 1, 10, 100, 1000, 2000)
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Entropy (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # ULDR (Seed: None, 1, 10, 100, 1000, 2000)
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # ULDR Cosine (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed None --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 1 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 10 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 100 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 1000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR10 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 2000 --download_path ./ --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True







#CIFAR 100 Stratified
    # Coreset Cosine (Seed: None, 1, 10, 100, 1000, 2000)
        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset_norm_cosine --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Coreset (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method coreset --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method coreset --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Random (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method random --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method random --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Softmax (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=2 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method softmax --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method softmax --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # Entropy (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method entropy --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=3 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method entropy --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # ULDR (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=1 python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

    # ULDR Cosine (Seed: None, 1, 10, 100, 1000, 2000)
        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed None --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 1 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 10 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 100 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 1000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True

        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme sequential --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set  --active_save_dir ./active_learners_val_set --verbose True --use_val_set True
        CUDA_VISIBLE_DEVICES=5python closed_set_active_learning.py CIFAR100 --training_method softmax_network --active_init_mode active --active_query_scheme independent --active_train_mode retrain --query_method uldr_norm_cosine --dataset_rand_seed 2000 --download_path /scratch --active_save_path ./active_datasets_val_set --active_save_dir ./active_learners_val_set --verbose True --use_val_set True


