
# CIFAR100 + ICALR + Half open active score
      # Update:
            # Currently only running entropy open on open_active_1 (3rd script for all active learning algo)
      # # Entropy active 
      #       # Softmax Open
      #             python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling none --arch ResNet18 --lr 0.1 --lr_decay_step 160 --epochs 200 --uncertainty_measure entropy --wd 5e-4 --open_active_setup half --threshold_metric softmax;
      #             python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling none --arch ResNet18 --lr 0.1 --lr_decay_step 160 --epochs 200 --uncertainty_measure entropy --wd 5e-4 --open_active_setup active --threshold_metric softmax;
      #             python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling none --arch ResNet18 --lr 0.1 --lr_decay_step 160 --epochs 200 --uncertainty_measure entropy --wd 5e-4 --open_active_setup hr100 --threshold_metric softmax;
      #             python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling none --arch ResNet18 --lr 0.1 --lr_decay_step 160 --epochs 200 --uncertainty_measure entropy --wd 5e-4 --open_active_setup hr200 --threshold_metric softmax;
      #             python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling none --arch ResNet18 --lr 0.1 --lr_decay_step 160 --epochs 200 --uncertainty_measure entropy --wd 5e-4 --open_active_setup hr300 --threshold_metric softmax;
      #             python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling none --arch ResNet18 --lr 0.1 --lr_decay_step 160 --epochs 200 --uncertainty_measure entropy --wd 5e-4 --open_active_setup open --threshold_metric softmax;
      # Learning Loss active 
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax; # Simple random query
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup open --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr100 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr200 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr300 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup ar100 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup ar200 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup ar300 --threshold_metric softmax;
            # Entropy Open
                  # python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup half --threshold_metric entropy;
      # Learning Loss active with lowest loss
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax; # Simple random query
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup open --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup hr100 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup hr200 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup hr300 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup ar100 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup ar200 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup ar300 --threshold_metric softmax;
            # Entropy Open
                  # python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup half --threshold_metric entropy;
      # Core set active 
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup open --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr100 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr200 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr300 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup ar100 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup ar200 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup ar300 --threshold_metric softmax;
            # Entropy Open
                  # python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup half --threshold_metric entropy;


# CIFAR100 + ICALR + Half open active score
      # Learning Loss active 
            # Softmax Open
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax; # Simple random query
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr100 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr200 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr300 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup ar100 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup ar200 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup ar300 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup open --threshold_metric softmax;
            # Entropy Open
                  # python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup half --threshold_metric entropy;
      # Core set active 
            # Softmax Open
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr100 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr200 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr300 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup ar100 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup ar200 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup ar300 --threshold_metric softmax;
                        python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup open --threshold_metric softmax;
            # Entropy Open
                  # python train.py CIFAR100 --max_rounds 400 --budget 20 --icalr_mode default --icalr_retrain_threshold 40 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_1 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup half --threshold_metric entropy;


# Two round!!

# CIFAR100 + ICALR + Half open active score
      # Learning Loss active 
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup open --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax; # This is just random query
      # Learning Loss active with lowest loss
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup active --threshold_metric softmax;
      # Core set active 
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy proto --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup open --threshold_metric softmax;

# CIFAR100 + ICALR + Half open active score
      # Learning Loss active 
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax; # Simple random query
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure highest_loss --wd 5e-4 --open_active_setup open --threshold_metric softmax;
      # Learning Loss active lowest loss
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 120 --data_path ./data --trainer icalr_learning_loss --learning_loss_train_mode default --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --uncertainty_measure lowest_loss --wd 5e-4 --open_active_setup half --threshold_metric softmax;
      # Core set active 
            # Softmax Open
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup active --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup half --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup hr400 --threshold_metric softmax;
                  python train.py CIFAR100 --max_rounds 2 --budget 7200 --icalr_mode default --icalr_retrain_threshold 1 --icalr_strategy naive --icalr_naive_strategy fixed --save_ckpt False --verbose True --log_everything True --init_mode open_active_0 --learning_loss_stop_epoch 0 --data_path ./data --trainer icalr --batch 128 --network_eval_threshold 0.02 --active_random_sampling fixed_10K --arch ResNet18 --lr 0.05 --lr_decay_step 160 --epochs 200 --label_picker coreset_measure --coreset_measure greedy --coreset_feature before_fc --wd 5e-4 --open_active_setup open --threshold_metric softmax;

